# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/golem/getHtml"
  to = "https://test.api.golem.cloud/golem/getHtml"
  status = 200