version: '3'

services:
  app:
    # Using a Dockerfile is optional, but included for completeness.
    deploy:
      resources:
        limits:
          cpus: '0.7'
    build: 
      context: .
      dockerfile: Dockerfile
      # [Optional] You can use build args to set options. e.g. 'VARIANT' below affects the image in the Dockerfile
      args: 
        VARIANT: bullseye
        WASM_BINDGEN_VERSION: "0.2.83"
        DOCKER_BUILDKIT: 1
    init: true
    volumes:
      # This is where VS Code should expect to find your project's source code and the value of "workspaceFolder" in .devcontainer/devcontainer.json
      - ..:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  
    user: vscode
    extra_hosts:
      - "localhost:172.17.0.1"
  nginx:
    image: nginx:1.24.0
    ports:
      - "4003:4003"
    deploy:
      resources:
        limits:
          cpus: '0.1'
    volumes:
      - ../certs:/certs
      - ../www:/var/www/html/static
      - ../nginx.conf:/etc/nginx/nginx.conf:ro